### PR TITLE
Add platform-specific check for keycloak_pid in test deployment

### PR DESCRIPTION
**Pull request by bengo237**

### CODE REVIEW

**Comment by francis-pouatcha** [comment]
This is one commit behind main. Can you please synch with main?

**Comment by bengo237** [comment]
The branch has been synchronized with the main branch.

**Comment by francis-pouatcha** [comment]
@bengo237 can you synchronize this with main?

**Comment by bengo237** [comment]
sync Done!

**Review by IngridPuppet — CHANGES_REQUESTED** [review]
There are signs of merge conflicts that weren't properly handled. Can you fix that?

**Review by IngridPuppet — APPROVED** [review]
LGTM

**Pull request merged**
